### PR TITLE
Update deploy-script.sh

### PR DESCRIPTION
**Pull request by t-abdul-basser**
include JTDS driver when loading JDBC drivers in the docker host volume mapped directory into the tomcat library

### CODE REVIEW

**Comment by leeevans** [comment]
@t-abdul-basser thanks for making this pull request.  

I'd like to take a more generic approach and broaden the pattern for copying in the jar files.  That way we won't have to make future changes for other jdbc driver file names and it provides an easy way for folks to include any other jars they need. 

Can you please update this pull request so we just have one copy statement:

`cp /tmp/drivers/*.jar /usr/local/tomcat/lib`

and I'll merge.

Thanks!
Lee

**Comment by t-abdul-basser** [comment]
Makes sense. Done.

**Comment by leeevans** [comment]
Merged. Thanks @t-abdul-basser

**Comment by t-abdul-basser** [comment]
Thanks @leeevans!

**Pull request merged**
